import { useEffect, useState } from "react";
import { Link } from "react-router";
import { useAuth } from "../auth/AuthContext.js";
type Rank = { position: number; id: number; name: string; department: string; reviewCount: number; averageRating: number };
export function RankingsPage() {
  const { apiFetch } = useAuth(); const [kind, setKind] = useState<"professors" | "disciplines">("professors"); const [items, setItems] = useState<Rank[]>([]); const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  useEffect(() => { const controller = new AbortController(); setState("loading"); apiFetch(`/api/rankings/${kind}`, { signal: controller.signal }).then(async r => { if (!r.ok) throw new Error(); if (!controller.signal.aborted) { setItems(await r.json()); setState("ready"); } }).catch(() => { if (!controller.signal.aborted) setState("error"); }); return () => controller.abort(); }, [apiFetch, kind]);
  return <main className="page-shell"><header className="page-header"><p className="eyebrow">Descoberta</p><h1>Rankings</h1></header><div className="moderation-tabs" role="tablist"><button role="tab" aria-selected={kind === "professors"} onClick={() => setKind("professors")}>Professores</button><button role="tab" aria-selected={kind === "disciplines"} onClick={() => setKind("disciplines")}>Disciplinas</button></div>{state === "loading" ? <p>Carregando ranking...</p> : null}{state === "error" ? <p role="alert">Não foi possível carregar o ranking.</p> : null}{state === "ready" && !items.length ? <p>Nenhum item com avaliações publicadas.</p> : null}{state === "ready" ? <ol className="review-list">{items.map(item => <li key={item.id} className="review-card"><strong>{item.position}º</strong> <Link to={`/${kind === "professors" ? "professors" : "disciplines"}/${item.id}`}>{item.name}</Link><p>{item.department} · {new Intl.NumberFormat("pt-BR", { minimumFractionDigits: 1, maximumFractionDigits: 1 }).format(item.averageRating)}/5 · {item.reviewCount} {item.reviewCount === 1 ? "avaliação" : "avaliações"}</p></li>)}</ol> : null}</main>;
}
